api/urls.py
from __future__ import annotations
from django.urls import path
from backend.mixins import VisitorTemplateView
from . import views

app_name = "api"

urlpatterns = [
    path('', VisitorTemplateView.as_view(template_name="api/doc.html"), name="doc"),
    path('people/', views.People.as_view(), name="people"),
    path('status/', views.Status.as_view(), name="status"),
    path('whoami/', views.Whoami.as_view(), name="whoami"),
    path('export_identities', views.ExportIdentities.as_view(), name="export_identities"),
    path('salsa_status/<int:subject>', views.SalsaStatus.as_view(), name="salsa_status"),
]

dm/urls.py
# coding: utf-8

from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="dm_index"),
    path('claim', views.Claim.as_view(), name="dm_claim"),
    path('claim/confirm/<token>', views.ClaimConfirm.as_view(), name="dm_claim_confirm"),
]

nm2/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView
from backend.mixins import VisitorTemplateView
from django.conf import settings
from rest_framework import routers
from django.contrib import admin
import django.conf.urls
import backend.views as bviews
import process.views as pviews
import public.views as public_views
import nmlayout.views as nmviews

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'persons', bviews.PersonViewSet, "persons")
router.register(r'processes', pviews.ProcessViewSet, "processes")

django.conf.urls.handler403 = nmviews.Error403.as_view()
django.conf.urls.handler404 = nmviews.Error404.as_view()
django.conf.urls.handler500 = nmviews.Error500.as_view()


urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    path('i18n/', include('django.conf.urls.i18n')),
    path(r'', VisitorTemplateView.as_view(template_name='index.html'), name="home"),
    path('license/', VisitorTemplateView.as_view(template_name='license.html'), name="root_license"),
    path('faq/', VisitorTemplateView.as_view(template_name='faq.html'), name="root_faq"),
    path('login/', RedirectView.as_view(url="/signon/login"), name='legacy_login'),
    path('members/', public_views.Members.as_view(), name="members"),
    path('legacy/', include("legacy.urls")),
    path('person/', include("person.urls")),
    path('public/', include("public.urls")),
    path('am/', include("restricted.urls")),
    path('fprs/', include("fprs.urls")),
    path('process/', include("process.urls")),
    path('dm/', include("dm.urls")),
    path('api/', include("api.urls")),
    path('apikeys/', include("apikeys.urls")),
    path('keyring/', include("keyring.urls")),
    path('wizard/', include("wizard.urls")),
    path('mia/', include("mia.urls")),
    path('minechangelogs/', include("minechangelogs.urls")),
    path('sitechecks/', include("sitechecks.urls")),
    path('deploy/', include("deploy.urls")),
    path('rest/api/', include(router.urls)),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

person/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = "person"

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="index"),
    path('<key>/', views.Person.as_view(), name="show"),
    path('<key>/edit_ldap/', views.EditLDAP.as_view(), name="edit_ldap"),
    path('<key>/edit_bio/', views.EditBio.as_view(), name="edit_bio"),
    path('<key>/edit_email/', views.EditEmail.as_view(), name="edit_email"),
    # AM preferences editor
    path('<key>/amprofile/', views.AMProfile.as_view(), name="amprofile"),
    path('<key>/certificate/', views.Certificate.as_view(), name="certificate"),
    path('identities/', views.Identities.as_view(), name='identities_self'),
    path('identities/<key>/', views.Identities.as_view(), name='identities'),
]

signon/urls.py
from django.urls import path
from . import views

app_name = "signon"

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('logout/<name>/', views.Logout.as_view(), name='logout_identity'),
    path('oidc/callback/<name>/', views.OIDCAuthenticationCallbackView.as_view(), name='oidc_callback'),
    path('whoami/', views.Whoami.as_view(), name='whoami'),
    path('link/<provider>/<int:pk>/', views.Link.as_view(), name='link'),
    path('unlink/<provider>/', views.Unlink.as_view(), name='unlink'),
]

wizard/urls.py
from __future__ import annotations
from django.urls import path
from backend.mixins import VisitorTemplateView
from . import views

app_name = "wizard"

urlpatterns = [
    path("", VisitorTemplateView.as_view(template_name="wizard/home.html"), name="home"),
    path("advocate/", views.Advocate.as_view(), name="advocate"),
    path("process/<applying_for>/", views.NewProcess.as_view(), name="newprocess"),
]

nmlayout/models.py
from django.db import models

# Create your models here.

nmlayout/views.py
from __future__ import annotations
import urllib.parse
from django.views.generic import TemplateView
from nmlayout.mixins import NM2LayoutMixin
from signon.views import LoginMixin
import logging

log = logging.getLogger(__name__)


class Error403(NM2LayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 403
            return res
        except Exception as e:
            log.error("403 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "403.html")]


class Error404(NM2LayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 404
            return res
        except Exception as e:
            log.error("404 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "404.html")]

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        exception_repr = self.kwargs["exception"].__class__.__name__
        # Try to get an "interesting" exception message, if any (and not the ugly
        # Resolver404 dictionary)
        try:
            message = self.kwargs["exception"].args[0]
        except (AttributeError, IndexError):
            pass
        else:
            if isinstance(message, str):
                exception_repr = message
        ctx['request_path'] = urllib.parse.quote(self.request.path)
        ctx['exception'] = exception_repr
        return ctx


class Error500(NM2LayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 500
            return res
        except Exception as e:
            log.error("500 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "500.html")]


class Login(LoginMixin, NM2LayoutMixin, TemplateView):
    template_name = "login.html"

nmlayout/templates/index.html
{% extends "nm2-base.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans "Debian New Members" %}</h1>

<p class="lead">
 {% blocktrans %}Welcome to the New Members website.{% endblocktrans %}
 {% blocktrans %}This is the place to apply for Debian membership, and to manage one's status in the project.{% endblocktrans %}
</p>

<div class="card-deck">

  <div class="card">
    <div class="card-header">
      {% trans "Main links" %}
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a href="{% url 'wizard:home' %}"><span class="fa fa-magic"></span> {% trans "Site wizard" %}</a>
        <p class="small mt-1">{% trans "Guided index to site features" %}</p>
      </li>
      <li class="list-group-item">
        <a href="{% url 'public_findperson' %}"><span class="fa fa-search"></span> {% trans "Find people" %}</a>
        <p class="small mt-1">{% trans "Search people known to the site" %}</p>
      </li>
      <li class="list-group-item">
        <a href="{% url 'members' %}"><span class="fa fa-certificate"></span> {% trans "Debian Members" %}</a>
        <p class="small mt-1">{% trans "Authoritative official list of Debian Members" %}</p>
      </li>
      <li class="list-group-item">
        <a href="{% url 'public_newnm' %}"><span class="fa fa-user-plus"></span> {% trans "Apply" context "verb; apply for membership" %}</a>
        <p class="small mt-1">{% trans "Apply for a status change through the site" %}</p>
      </li>
    </ul>
  </div>

  <div class="card">
    <div class="card-header">
      {% trans "Processes" %}
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a href="{% url 'process_list' %}"><span class="fa fa-group"></span> {% trans "Applications" %}</a>
        <p class="small mt-1">{% trans "List of open and recent processes" %}</p>
      </li>
      <li class="list-group-item">
        <a href="{% url 'managers' %}"><span class="fa fa-address-card"></span> {% trans "Managers" %}</a>
        <p class="small mt-1">{% trans "Debian Members who volunteer to review applicants" %}</p>
      </li>
      {% if user.is_authenticated and user.is_am %}
      <li class="list-group-item">
        <a href="{% url 'process_am_dashboard' %}"><span class="fa fa-dashboard"></span> {% trans "AM dashboard" %}</a>
        <p class="small mt-1">{% trans "Your main page as Application Manager" %}</p>
      </li>
      {% endif %}
      <li class="list-group-item">
        <a href="https://wiki.debian.org/Keysigning"><span class="fa fa-key"></span> {% trans "Keysigning" %}</a>
        <p class="small mt-1">{% trans "GPG key signing coordination" %}</p>
      </li>
      <li class="list-group-item">
        <a href="https://wiki.debian.org/Teams/FrontDesk"><span class="fa fa-envelope"></span> {% trans "Contact" %}</a>
        <p class="small mt-1">{% trans "New Member Front Desk contact information" %}</p>
      </li>
    </ul>
  </div>

  <div class="card">
    <div class="card-header">
      {% trans "Data" %}
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a href="{% url 'public_stats' %}"><span class="fa fa-pie-chart"></span> {% trans "Site statistics" %}</a>
        <p class="small mt-1">{% trans "Current and historical statistics about the site" %}</p>
      </li>
      {% if user.is_authenticated %}
      <li class="list-group-item">
        <a href="{% url 'minechangelogs:search_self' %}"><span class="fa fa-history"></span> {% trans "Changelogs search" %}</a>
        <p class="small mt-1">{% trans "Search package changelogs" %}</p>
      </li>
      {% endif %}
      {% if user.is_authenticated and user.is_dd %}
      <li class="list-group-item">
        <a href="{% url 'restricted_db_export' %}"><span class="fa fa-download"></span> {% trans "Export" %}</a>
        <p class="small mt-1">{% trans "Database export for development" %}</p>
      </li>
      {% endif %}
    </ul>
  </div>

  <div class="card">
    <div class="card-header">
      {% trans "Site" %}
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a href="{% url 'root_faq' %}"><span class="fa fa-question"></span> {% trans "FAQ" %}</a>
        <p class="small mt-1">{% trans "Frequently Asked Questions" %}</p>
      </li>
      <li class="list-group-item">
        <a href="https://salsa.debian.org/nm-team/nm.debian.org"><span class="fa fa-code"></span> {% trans "Development" %}</a>
        <p class="small mt-1">{% trans "GitLab project page for the site" %}</p>
      </li>
      <li class="list-group-item">
        <a href="http://bugs.debian.org/nm.debian.org"><span class="fa fa-bug"></span> {% trans "Bugs" %}</a>
        <p class="small mt-1">{% trans "Site issue tracker" %}</p>
      </li>
    </ul>
  </div>

</div>

{% endblock %}

nmlayout/templates/login.html
{% extends "nm2-base.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans "nm.debian.org login" %}</h1>

{% include "signon/login.html" %}

{% endblock %}

nmlayout/templates/nm-langs_snippet.html
{% load i18n %}

{% get_current_language as cur_lang %}
{% get_available_languages as languages %}
{% get_language_info_list for languages as langs %}
<div id="langselector" class="modalDialog">
  <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
  <input type="hidden" name="next" value="{{request.path}}" />
  {% trans "This page is also available in the following languages:" %}
  {% for l in langs %}
  <button class="{% if cur_lang == l.code %}current{% endif %}"
      title="{% trans l.name %}" name="language" value="{{l.code}}">{{l.name_local}}</button>{% if not forloop.last %}, {% endif %}
  {% endfor %}
  </form>
</div>

nmlayout/templates/nm2-base.html
{% extends "debian-bootstrap4-base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_brand_url %}{% url 'home' %}{% endblock %}

{% block title %}{% trans "Debian New Member Process" %}{% endblock %}

{% block head %}
{{block.super}}
<link rev="made" href="mailto:nm@debian.org">
<link type="text/css" rel="stylesheet" media="all" href="{% static "css/nm2.css" %}">
{{ALL_STATUS|json_script:"ALL_STATUS"}}
<script src="{% static "js/nm.js" %}"></script>
<script type="text/javascript">
(function() {
"use strict";
window.nm2.url_api_people = "{% url 'api:people' %}";
})();
</script>
{% endblock %}

{% block nav_searchbox %}{% comment %}No search feature in NM site yet{% endcomment %}{% endblock %}

{% block nav_left_items %}{# Top links #}
  <li class="nav-item"><a class="nav-link" href="{% url 'public_findperson' %}"><span class="fa fa-search"></span> {% trans "People" %}</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'wizard:home' %}"><span class="fa fa-magic"></span> {% trans "Site wizard" %}</a></li>
  {% if user.is_am %}
  <li class="nav-item"><a class="nav-link" href="{% url 'process_am_dashboard' %}"><span class="fa fa-dashboard"></span> {% trans "AM dashboard" %}</a></li>
  {% endif %}
  {% if wikihelp %}<li><a class="nav-link" href="{{wikihelp}}"><span class="fa fa-info"></span> {% trans "Wiki help" %}<a/a></li>{% endif %}
  {% if navbar.person %} {# Person dropdown menu #}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="fa fa-user"></span> {{person.lookup_key}}
    </a>
    <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdown">
    {% for link in navbar.person %}
      <a class=
     {% if link.disabled %}
        "dropdown-item disabled"
     {% else  %}
        "dropdown-item"
     {% endif %}
     {% if link.target_blank %}
         target="_blank"
     {% endif %}
      href="{{link.url}}">{% if link.icon %}<span class="fa fa-{{link.icon}}"></span> {% endif %}{{link.label}}</a>
    {% endfor %}
    {% if user != person %}
    <form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
      <input type="hidden" name="pk" value="{{person.pk}}">
      <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
      <button class="dropdown-item btn btn-link" type="submit"><span class="fa fa-random"></span> {% trans "Impersonate" %}</button>
    </form>
    {% endif %}
    </div>
  </li>
  {% endif %}
  {% if navbar.process %} {# Process dropdown menu #}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="fa fa-drivers-license"></span> {% trans "Process" %}
    </a>
    <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdown">
    {% for link in navbar.process %}
      <a class="dropdown-item" href="{{link.url}}">{% if link.icon %}<span class="fa fa-{{link.icon}}"></span> {% endif %}{{link.label}}</a>
    {% endfor %}
    </div>
  </li>
  {% endif %}
{% endblock %}

{% block nav_right_items %}{# Visitor menu #}

{% if user.is_anonymous and not request.signon_identities %}
<li class="nav-item"><a href="{% url 'signon:login' %}"><span class="fa fa-sign-in"></span> {% trans "Login" %}</a></li>
{% else %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="fa fa-user-circle"></span>
  {% if user.is_anonymous %}
    {{request.sso_username}}
    {% trans "(not known to this site yet)" %}
  {% else %}
    {{user.lookup_key}}
  {% endif %}
  </a>
  <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="navbarDropdown">
  {% block visitor_menu %}
    {% if request.impersonator %}
    <form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
      <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
      <button class="dropdown-item btn btn-link" type="submit"><span class="fa fa-random"></span> (really {{request.impersonator.lookup_key}})</button>
    </form>
    {% endif %}
    {% if user.is_anonymous %}
      <a class="dropdown-item" href="{% url 'dm_claim' %}">{% trans "claim account" %}</a>
    {% else %}
      <a class="dropdown-item" href="{{user.get_absolute_url}}"><span class="fa fa-user"></span> {% trans "Personal page" %}</a>
      {% if user.is_am %}
      <a class="dropdown-item" href="{% url 'process_am_dashboard' %}"><span class="fa fa-dashboard"></span> {% trans "AM dashboard" %}</a>
      <a class="dropdown-item" href="{% url 'person:amprofile' key=user.lookup_key %}"><span class="fa fa-gear"></span> {% trans "AM profile" %}</a>
      {% endif %}
    {% endif %}
    <a class="dropdown-item" href="{{user.get_ddpo_url}}" target="_blank"><span class="fa fa-tasks"></span> {% trans "DDPO" %}</a>
    <a class="dropdown-item" href="{{user.get_portfolio_url}}" target="_blank"><span class="fa fa-newspaper-o"></span> {% trans "Portfolio" %}</a>
    {% if user.get_contributors_url %}<a class="dropdown-item" href="{{user.get_contributors_url}}" target="_blank"><span class="fa fa-address-card"></span> {% trans "Contributor" %}</a>{% endif %}
    {% if user.is_authenticated %}<a class="dropdown-item" href="{% url 'minechangelogs:search' key=user.lookup_key %}" target="_blank"><span class="fa fa-history"></span> {% trans "Changelogs" %}</a>{% endif %}
    {% if user.is_superuser %}<a class="dropdown-item" href="{{user.get_admin_url}}"><span class="fa fa-microchip"></span> {% trans "Admin" %}</a>{% endif %}
    {% if user.is_dd %}
      {% if emeritus_link %}<a class="dropdown-item" href="{{emeritus_link}}">{% trans "One click emeritus" %}</a>{% endif %}
    {% endif %}
    <a class="dropdown-item" href="{% url 'signon:login' %}"><span class="fa fa-sign-in"></span> {% trans "Logins" %}</a>
    <form class="form-inline" method="POST" action="{% url "signon:logout" %}">{% csrf_token %}
      <button class="btn btn-link dropdown-item" method="submit"><span class="fa fa-sign-out"></span> {% trans "Logout" %}</button>
    </form>
  {% endblock %}
  </div>
</li>
{% endif %}

{% endblock %}

{% block content %}
<h1>{% trans "Debian NM Website Template" %}</h1>
{% endblock %}

{% block page_lead %}
{{super}}
{% if request.impersonator %}
<div id="impersonation" class="container-fluid bg-warning">
<span class="badge badge-pill badge-light"><span class="fa fa-random"></span> {{request.impersonator.a_link}} as {{user.a_link}}</span>
<form class="form-inline" method="POST" action="{% url 'impersonate:impersonate' %}">{% csrf_token %}
  <input type="hidden" name="next" value="{{request.build_absolute_uri}}">
  <button class="badge badge-pill badge-primary" type="submit">{% trans "Cancel" %}</button>
</form>
{% for perm in visit_perms %}<span class="badge badge-pill badge-info mr-1">{{perm}}</span>{% endfor %}
</div>
{% endif %}

{% comment %}
{% if request.signon_identities %}
<div id="signon" class="container-fluid bg-info">
  {% for name, identity in request.signon_identities.items %}
  <div class="badge badge-pill badge-success">
    {% if identity.picture %}<img style="height: 2ex" class="mr-2" src="{{identity.picture}}"></img>{% endif %}
    Logged in with {{identity.get_provider.name}} as <a href="{{identity.profile}}">{{identity.fullname}}</a>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endcomment %}

{# {% if messages %} #}
<div aria-live="polite" aria-atomic="true" class="position-relative">
  <div style="position: absolute; top: 0; right: 0;">
    {% with ERROR=DEFAULT_MESSAGE_LEVELS.ERROR %}
    {% for message in messages %}
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header{% if message.level == ERROR %} bg-danger{% endif %}">
        <span class={% if message.level == ERROR %}"fa fa-exclamation-circle mr-1"{% else %}"fa fa-info-circle mr-1"{% endif %}></span>
        <strong class="mr-auto">{{message.level_tag}}</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body" >
        {{message}}
      </div>
    </div>
    {% endfor %}
    {% endwith %}
  </div>
</div>
{# {% endif %} #}
{% endblock %}

{% block footer %}
<div class="card-body">
{% url 'root_license' as root_license_url %}
<p class="card-text"><small>
{% blocktrans with root_license_url=root_license_url %}
<a href="{{root_license_url}}">Copyright</a> © 2012--2020 <a href="https://wiki.debian.org/Teams/FrontDesk">Debian Front Desk</a>.
Source code is <a href="https://salsa.debian.org/nm-team/nm.debian.org">available on Salsa</a>.
Report bugs on <a href="https://salsa.debian.org/nm-team/nm.debian.org/-/issues">Salsa</a> or the <a href="http://bugs.debian.org/nm.debian.org">Debian BTS</a>.
{% endblocktrans %}
</small>
</p>

{% get_current_language as cur_lang %}
{% get_available_languages as languages %}
{% get_language_info_list for languages as langs %}
<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
<input type="hidden" name="next" value="{{request.path}}" />
<p class="card-text"><small>
{% trans "This page is also available in the following languages:" %}
{% for l in langs %}
<button class="btn btn-link m-0 p-0 border-0 {% if cur_lang == l.code %}current{% endif %}"
    title="{% trans l.name %}" name="language" value="{{l.code}}">{{l.name_local}}</button>{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
</form>
</div>
{% endblock %}