dm/urls.py
# coding: utf-8

from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="dm_index"),
    path('claim', views.Claim.as_view(), name="dm_claim"),
    path('claim/confirm/<token>', views.ClaimConfirm.as_view(), name="dm_claim_confirm"),
]

fprs/urls.py
from __future__ import annotations
from django.urls import path, re_path
from . import views

app_name = "fprs"

urlpatterns = [
    # Manage fingerprints
    path('person/<key>/', views.PersonFingerprints.as_view(), name="person_list"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/view/$', views.ViewKeyEndorsements.as_view(), name="view_endorsements"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/add/$', views.EndorseKey.as_view(), name="endorse"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/(?P<endorsement>[0-9]+)/raw/$', views.ViewRawKeyEndorsement.as_view(), name="view_raw_endorsement"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/(?P<endorsement>[0-9]+)/delete/$', views.DeleteKeyEndorsement.as_view(), name="delete_endorsement"),
    # Activate fingerprints
    re_path(r'^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/activate/$', views.SetActiveFingerprint.as_view(),
            name="person_activate"),
]

legacy/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "legacy"

urlpatterns = [
    path('process/<key>/', views.Process.as_view(), name="process"),
    path('mail-archive/<key>/', views.MailArchive.as_view(), name="download_mail_archive"),
    path('display-mail-archive/<key>/', views.DisplayMailArchive.as_view(), name="display_mail_archive"),
]

nm2/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView
from backend.mixins import VisitorTemplateView
from django.conf import settings
from rest_framework import routers
from django.contrib import admin
import django.conf.urls
import backend.views as bviews
import process.views as pviews
import public.views as public_views
import nmlayout.views as nmviews

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'persons', bviews.PersonViewSet, "persons")
router.register(r'processes', pviews.ProcessViewSet, "processes")

django.conf.urls.handler403 = nmviews.Error403.as_view()
django.conf.urls.handler404 = nmviews.Error404.as_view()
django.conf.urls.handler500 = nmviews.Error500.as_view()


urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    path('i18n/', include('django.conf.urls.i18n')),
    path(r'', VisitorTemplateView.as_view(template_name='index.html'), name="home"),
    path('license/', VisitorTemplateView.as_view(template_name='license.html'), name="root_license"),
    path('faq/', VisitorTemplateView.as_view(template_name='faq.html'), name="root_faq"),
    path('login/', RedirectView.as_view(url="/signon/login"), name='legacy_login'),
    path('members/', public_views.Members.as_view(), name="members"),
    path('legacy/', include("legacy.urls")),
    path('person/', include("person.urls")),
    path('public/', include("public.urls")),
    path('am/', include("restricted.urls")),
    path('fprs/', include("fprs.urls")),
    path('process/', include("process.urls")),
    path('dm/', include("dm.urls")),
    path('api/', include("api.urls")),
    path('apikeys/', include("apikeys.urls")),
    path('keyring/', include("keyring.urls")),
    path('wizard/', include("wizard.urls")),
    path('mia/', include("mia.urls")),
    path('minechangelogs/', include("minechangelogs.urls")),
    path('sitechecks/', include("sitechecks.urls")),
    path('deploy/', include("deploy.urls")),
    path('rest/api/', include(router.urls)),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

legacy/models.py
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import utc, now
from django.db import models
from django.urls import reverse
from django.conf import settings
from backend.models import Person, AM
from backend import const
from backend import permissions
import os
import datetime


class Process(models.Model):
    """
    A process through which a person gets a new status

    There can be more than one Process per Person, but only one of them can be
    active at any one time. This is checked during maintenance.
    """
    person = models.ForeignKey(Person, related_name="legacy_processes", on_delete=models.CASCADE)

    applying_as = models.CharField("original status", max_length=20, null=False,
                                   choices=[x[1:3] for x in const.ALL_STATUS])
    applying_for = models.CharField("target status", max_length=20, null=False,
                                    choices=[x[1:3] for x in const.ALL_STATUS])
    progress = models.CharField(max_length=20, null=False,
                                choices=[x[1:3] for x in const.ALL_PROGRESS])

    # This is NULL until one gets a manager
    manager = models.ForeignKey(AM, related_name="+", null=True, blank=True, on_delete=models.PROTECT)

    advocates = models.ManyToManyField(Person, related_name="+", blank=True,
                                       limit_choices_to={"status__in": (const.STATUS_DD_U, const.STATUS_DD_NU)})

    # True if progress NOT IN (PROGRESS_DONE, PROGRESS_CANCELLED)
    is_active = models.BooleanField(null=False, default=False)

    closed = models.DateTimeField(
            null=True, blank=True, help_text=_("Date the process was closed, or NULL if still open"))

    archive_key = models.CharField("mailbox archive key", max_length=128, null=False, unique=True)

    def save(self, *args, **kw):
        if not self.archive_key:
            ts = now().strftime("%Y%m%d%H%M%S")
            if self.person.ldap_fields.uid:
                self.archive_key = "-".join((ts, self.applying_for, self.person.ldap_fields.uid))
            else:
                self.archive_key = "-".join((ts, self.applying_for, self.person.email))
        super(Process, self).save(*args, **kw)

    def __str__(self):
        return "{} to become {} ({})".format(
            str(self.person),
            const.ALL_STATUS_DESCS.get(self.applying_for, self.applying_for),
            const.ALL_PROGRESS_DESCS.get(self.progress, self.progress),
        )

    def __repr__(self):
        return "{} {}->{}".format(
            self.person.lookup_key,
            self.person.status,
            self.applying_for)

    def get_absolute_url(self):
        return reverse("legacy:process", kwargs=dict(key=self.lookup_key))

    def get_admin_url(self):
        return reverse("admin:backend_process_change", args=[self.pk])

    @property
    def a_link(self):
        from django.utils.safestring import mark_safe
        from django.utils.html import conditional_escape
        return mark_safe("<a href='{}'>→ {}</a>".format(
            conditional_escape(self.get_absolute_url()),
            conditional_escape(const.ALL_STATUS_DESCS[self.applying_for])))

    @property
    def lookup_key(self):
        """
        Return a key that can be used to look up this process in the database
        using Process.lookup.

        Currently, this is the email if the process is active, else the id.
        """
        return str(self.id)

    @classmethod
    def lookup(cls, key):
        # Key can either be a Process ID or a person's lookup key
        if key.isdigit():
            try:
                return cls.objects.get(id=int(key))
            except cls.DoesNotExist:
                return None
        else:
            # If a person's lookup key is used, and there is only one active
            # process, return that one. Else, return the most recent process.
            p = Person.lookup(key)
            if p is None:
                return None

            # If we reach here, either we have one process, or a new process
            # has been added # changed since the URL was generated. We have an
            # ambiguous situation, which we handle blissfully arbitrarily
            try:
                from django.db.models import Max
                return p.legacy_processes.annotate(last_change=Max("log__logdate")).order_by("-last_change")[0]
            except IndexError:
                return None

    @classmethod
    def lookup_or_404(cls, key):
        from django.http import Http404
        res = cls.lookup(key)
        if res is not None:
            return res
        raise Http404

    @property
    def mailbox_file(self):
        """
        The pathname of the archival mailbox, or None if it does not exist
        """
        PROCESS_MAILBOX_DIR_OLD = getattr(settings, "PROCESS_MAILBOX_DIR_OLD", "/srv/nm.debian.org/mbox/applicants/")
        fname = os.path.join(PROCESS_MAILBOX_DIR_OLD, self.archive_key) + ".mbox"
        if os.path.exists(fname):
            return fname
        return None

    @property
    def mailbox_mtime(self):
        """
        The mtime of the archival mailbox, or None if it does not exist
        """
        fname = self.mailbox_file
        if fname is None:
            return None
        return datetime.datetime.utcfromtimestamp(os.path.getmtime(fname)).replace(tzinfo=utc)

    @property
    def archive_email(self):
        if self.person.ldap_fields.uid:
            key = self.person.ldap_fields.uid
        else:
            key = self.person.email.replace("@", "=")
        return "archive-{}@nm.debian.org".format(key)

    def permissions_of(self, visitor):
        """
        Compute which LegacyProcessVisitorPermissions \a visitor has over this process
        """
        if visitor.is_authenticated:
            return permissions.LegacyProcessVisitorPermissions(self, visitor)
        else:
            return permissions.LegacyProcessVisitorPermissions(self, None)


class Log(models.Model):
    """
    A log entry about anything that happened during a process
    """
    changed_by = models.ForeignKey(Person, related_name="+", null=True, on_delete=models.CASCADE)
    process = models.ForeignKey(Process, related_name="log", on_delete=models.CASCADE)

    # Copied from Process when the log entry is created
    progress = models.CharField(max_length=20, null=False,
                                choices=[(x.tag, x.ldesc) for x in const.ALL_PROGRESS])

    is_public = models.BooleanField(default=False, null=False)
    logdate = models.DateTimeField(null=False, default=now)
    logtext = models.TextField(null=False, blank=True, default="")

    def __str__(self):
        return "{}: {}".format(self.logdate, self.logtext)

legacy/views.py
from django import http
from django.conf import settings
from django.views.generic import View, TemplateView
from .mixins import VisitProcessMixin, VisitProcessTemplateView
import backend.email
import datetime
import os
import json


class Process(VisitProcessTemplateView):
    template_name = "legacy/process.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        # Process form ASAP, so we compute the rest with updated values
        am = self.request.user.am_or_none if self.request.user.is_authenticated else None

        log = list(self.process.log.order_by("logdate", "progress"))
        if log:
            ctx["started"] = log[0].logdate
            ctx["last_change"] = log[-1].logdate
        else:
            ctx["started"] = datetime.datetime(1970, 1, 1, 0, 0, 0)
            ctx["last_change"] = datetime.datetime(1970, 1, 1, 0, 0, 0)

        if am:
            ctx["log"] = log
        else:
            # Summarise log for privacy
            distilled_log = []
            last_progress = None
            for l in log:
                if last_progress != l.progress:
                    distilled_log.append(dict(
                        progress=l.progress,
                        changed_by=l.changed_by,
                        logdate=l.logdate,
                    ))
                    last_progress = l.progress
            ctx["log"] = distilled_log

        # Mailbox statistics
        # TODO: move saving per-process stats into a JSON field in Process
        try:
            with open(os.path.join(settings.DATA_DIR, 'mbox_stats.json'), "rt") as infd:
                stats = json.load(infd)
        except OSError:
            stats = {}

        stats = stats.get("process", {})
        stats = stats.get(self.process.lookup_key, {})
        if stats:
            stats["date_first_py"] = datetime.datetime.fromtimestamp(stats["date_first"])
            stats["date_last_py"] = datetime.datetime.fromtimestamp(stats["date_last"])
            if "median" not in stats or stats["median"] is None:
                stats["median_py"] = None
            else:
                stats["median_py"] = datetime.timedelta(seconds=stats["median"])
                stats["median_hours"] = stats["median_py"].seconds // 3600
        ctx["mbox_stats"] = stats

        return ctx


class MailArchive(VisitProcessMixin, View):
    require_visit_perms = "view_mbox"

    def get(self, request, key, *args, **kw):
        fname = self.process.mailbox_file
        if fname is None:
            raise http.Http404

        user_fname = "%s.mbox" % (self.process.person.ldap_fields.uid or self.process.person.email)

        res = http.HttpResponse(content_type="application/octet-stream")
        res["Content-Disposition"] = "attachment; filename=%s.gz" % user_fname

        # Compress the mailbox and pass it to the request
        from gzip import GzipFile
        import shutil
        # The last mtime argument seems to only be supported in python 2.7
        outfd = GzipFile(user_fname, "wb", 9, res)
        try:
            with open(fname, "rb") as infd:
                shutil.copyfileobj(infd, outfd)
        finally:
            outfd.close()
        return res


class DisplayMailArchive(VisitProcessMixin, TemplateView):
    template_name = "process/display-mail-archive.html"
    require_visit_perms = "view_mbox"

    def get_context_data(self, **kw):
        ctx = super(DisplayMailArchive, self).get_context_data(**kw)

        fname = self.process.mailbox_file
        if fname is None:
            raise http.Http404

        ctx["mbox"] = backend.email.StoredEmail.get_mbox_jsonable(fname)
        ctx["class"] = "clickable"
        return ctx

legacy/templates/legacy/display-mail-archive.html
{% extends "nm2-base.html" %}
{% load nm %}
{% load i18n %}
{% load none_if_epoch %}

{% block head %}
{{block.super}}
<script type="text/javascript">
$(function() {

    var mailstable = $("#mailstable");

//    mailstable.tablesorter({
//        textExtraction: function(node) {
//            val = node.getAttribute("val");
//            if (val == null)
//                val = node.textContent || node.innerText;
//            return val;
//        },
//    });

    mailstable.find("tr.clickable").click(function(ev) {
      var el = $(this);
      el.next(".showable").toggle();
    });

    $("tr.showable").click(function(ev) { $(this).toggle(); });

});
</script>
{% endblock %}

{% block content %}

<h1>Mail archive</h1>

(Click to see the message body)

<table id="mailstable" class="table table-sm">
<thead>
    <tr>
        <th>Date</th>
        <th>From</th>
        <th>Subject</th>
    </tr>
</thead>
<tbody>
    {% for m in mails %}
    <tr class="{{class}}">
        <td>{{m.Date}}</td>
        <td>{{m.From}}</td>
        <td>{{m.Subject}}</td>
    </tr>
    <tr class="showable"><td colspan="3">{{m.Body|linebreaks}}</tr>
    {% empty %}
    <tr>{% trans "Sorry, this is really strange, no messages in archive." %}<tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

legacy/templates/legacy/process.html
{% extends "nm2-base.html" %}
{% load nm %}
{% load i18n %}

{% block content %}

<h1>{% blocktrans with name=person.fullname %}Application status for {{ name }}{% endblocktrans %}</h1>


<h2>{% trans "Personal information" %}</h2>

<table class="table table-sm">
    <tr><th>{% trans "Applicant" %}</th><td><a href="{{person.get_absolute_url}}">{{person.fullname}} &lt;{{person.preferred_email}}&gt;</a></td></tr>
    <tr><th>{% trans "Received application" %}</th><td>{{started|date:"Y-m-d"}}</td></tr>
    <tr><th>{% trans "Time of Last Action" %}</th><td>{{last_change|date:"Y-m-d"}}</th></tr>
    <tr>
    <th>{% trans "Advocate" %}{{process.advocates.count|pluralize}}</th>
        <td>
            {% for a in process.advocates.all %}
            <a href="{{ a.get_absolute_url }}">{{a.person.ldap_fields.uid}}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </td>
    </tr>
    <tr><th>{% trans "Account name" %}</th><td>{{person.ldap_fields.uid|default:"none chosen yet"}}</td></tr>
    {% with fpr=person.fingerprint %}
    <tr>
      <th>{% trans "OpenPGP fingerprint" %}</th>
      <td>
        {{fpr.fpr|fingerprint}}{% if "edit_fpr" in visit_perms %} (<a href="{% url 'fprs:person_list' key=person.lookup_key %}">{% trans "manage" context "verb; link to manage this person" %}</a>){% endif %}
        {% if fpr %}
        <small>
        <ul class="packed">
          {% if keycheck %}
          <li>{% trans "Main key:" %} <i>{{keycheck.main.remarks}}</i> ({% trans "last updated:" %} {{keycheck.updated|date:"Y-m-d H:i T"}})</li>
          {% for uid in keycheck.uids %}
          <li>{{uid.name}}: <i>{{uid.remarks}}</i>, <i>{{uid.sigs_ok}}</i> {% trans "DD sigs" %}, <i>{{uid.sigs_no_key}}</i> {% trans "non-DD sigs" %}</li>
          {% endfor %}
          {% endif %}
        </ul>
        </small>
        {% endif %}
      </td>
    </tr>
    {% endwith %}
    {% if process.manager %}
    <tr><th>{% trans "Manager" %}</th><td><a href="{{process.manager.get_absolute_url}}">{{process.manager.person.ldap_fields.uid}}</a></td></tr>
    {% endif %}
    <tr><th>{% trans "Process" %}</th><td>{{process.applying_as|desc_status}} → {{process.applying_for|desc_status}}</td></tr>
    <tr><th>{% trans "Progress" %}</th><td>{{process.progress|desc_progress}}</td></tr>
    <tr><th>{% trans "Account created" %}</th><td>{% if process.progress == PROGRESS_DONE %}{% trans "yes" %}{% else %}{% trans "no" %}{% endif %}</td></tr>
    {% if user.is_superuser %}
    <tr><th>{% trans "FD comments" %}</th><td>{{person.fd_comment}}</td></tr>
    {% endif %}
    {% if "view_mbox" in visit_perms %}
    <tr><th>{% trans "Mail archive" %}</th>
        <td>
            <code><a href="mailto:{{process.archive_email}}">{{process.archive_email}}</a></code>
            {% if process.mailbox_file %}
            <a href="{% url 'legacy:download_mail_archive' key=process.lookup_key %}">{% trans "(download mail archive)" %}</a>
            <a href="{% url 'legacy:display_mail_archive' key=process.lookup_key %}">{% trans "(display mail archive)" %}</a>
            {% else %}
            {% trans "(no mail archive yet)" %}
            {% endif %}
        </td>
    </tr>
    {% if mbox_stats %}
    <tr><th>{% trans "Mailbox stats" %}</th>
        <td>{{mbox_stats.date_first_py|date:"Y-m-d"}} {% trans "to" %} {{mbox_stats.date_last_py|date:"Y-m-d"}},
            {{mbox_stats.num_mails}} {% trans "mails," %}
            <br>
            {% if mbox_stats.median_py %}
              {% if mbox_stats.median_py.days %}{{mbox_stats.median_py.days}}d {% endif %}{{mbox_stats.median_hours}}h {% trans "median response time" %}
            {% endif %}
            <span class="mbox_sparkline" values="{{mbox_stats.response_time|join:","}}"></span>
        </td>
    </tr>
    {% endif %}
    {% endif %}
</table>


<h2>{% trans "Process log" %}</h2>

<table class="table table-sm">
<thead>
    <tr>
        {% if user.is_superuser %}
        <th>{% trans "Actions" %}</th>
        {% endif %}
        <th>{% trans "Date" %}</th>
        <th>{% trans "Changed by" %}</th>
        <th>{% trans "Progress" %}</th>
        {% if user.am %}
        <th>{% trans "Text" %}</th>
        {% endif %}
    </tr>
</thead>
<tbody>
    {% for l in log %}
    <tr>
        {% if user.is_superuser %}
        <td><a href="{% url 'admin:legacy_log_change' l.id %}">{% trans "edit" %}</a></td>
        {% endif %}
        <td>{{l.logdate|date:"Y-m-d"}}</td>
        <td>
            <a href="{{l.changed_by.get_absolute_url}}">{{l.changed_by.person.ldap_fields.uid}}</a>
        </td>
        <td>{{l.progress|desc_progress}}</td>
        {% if user.am %}
        <td>{{l.logtext}}</td>
        {% endif %}
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}