api/urls.py
from __future__ import annotations
from django.urls import path
from backend.mixins import VisitorTemplateView
from . import views

app_name = "api"

urlpatterns = [
    path('', VisitorTemplateView.as_view(template_name="api/doc.html"), name="doc"),
    path('people/', views.People.as_view(), name="people"),
    path('status/', views.Status.as_view(), name="status"),
    path('whoami/', views.Whoami.as_view(), name="whoami"),
    path('export_identities', views.ExportIdentities.as_view(), name="export_identities"),
    path('salsa_status/<int:subject>', views.SalsaStatus.as_view(), name="salsa_status"),
]

apikeys/urls.py
from __future__ import annotations
from django.urls import path
from . import views

app_name = "apikeys"

urlpatterns = [
    path('', views.KeyList.as_view(), name="list"),
    path('<int:pk>/enable/', views.KeyEnable.as_view(), name="enable"),
    path('<int:pk>/delete/', views.KeyDelete.as_view(), name="delete"),
]

dm/urls.py
# coding: utf-8

from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="dm_index"),
    path('claim', views.Claim.as_view(), name="dm_claim"),
    path('claim/confirm/<token>', views.ClaimConfirm.as_view(), name="dm_claim_confirm"),
]

nm2/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView
from backend.mixins import VisitorTemplateView
from django.conf import settings
from rest_framework import routers
from django.contrib import admin
import django.conf.urls
import backend.views as bviews
import process.views as pviews
import public.views as public_views
import nmlayout.views as nmviews

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'persons', bviews.PersonViewSet, "persons")
router.register(r'processes', pviews.ProcessViewSet, "processes")

django.conf.urls.handler403 = nmviews.Error403.as_view()
django.conf.urls.handler404 = nmviews.Error404.as_view()
django.conf.urls.handler500 = nmviews.Error500.as_view()


urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    path('i18n/', include('django.conf.urls.i18n')),
    path(r'', VisitorTemplateView.as_view(template_name='index.html'), name="home"),
    path('license/', VisitorTemplateView.as_view(template_name='license.html'), name="root_license"),
    path('faq/', VisitorTemplateView.as_view(template_name='faq.html'), name="root_faq"),
    path('login/', RedirectView.as_view(url="/signon/login"), name='legacy_login'),
    path('members/', public_views.Members.as_view(), name="members"),
    path('legacy/', include("legacy.urls")),
    path('person/', include("person.urls")),
    path('public/', include("public.urls")),
    path('am/', include("restricted.urls")),
    path('fprs/', include("fprs.urls")),
    path('process/', include("process.urls")),
    path('dm/', include("dm.urls")),
    path('api/', include("api.urls")),
    path('apikeys/', include("apikeys.urls")),
    path('keyring/', include("keyring.urls")),
    path('wizard/', include("wizard.urls")),
    path('mia/', include("mia.urls")),
    path('minechangelogs/', include("minechangelogs.urls")),
    path('sitechecks/', include("sitechecks.urls")),
    path('deploy/', include("deploy.urls")),
    path('rest/api/', include(router.urls)),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

api/models.py
from django.db import models

# Create your models here.

api/views.py
from __future__ import annotations
from django import http
from django.core.exceptions import PermissionDenied
from django.forms.models import model_to_dict
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
import backend.models as bmodels
from apikeys.mixins import APIVisitorMixin
import json
import logging

log = logging.getLogger(__name__)


class Serializer(json.JSONEncoder):
    def default(self, o):
        if hasattr(o, "strftime"):
            return o.strftime("%s")
            # return o.strftime("%Y-%m-%d %H:%M:%S")
        return json.JSONEncoder.default(self, o)


def json_response(val, status_code=200):
    res = http.HttpResponse(content_type="application/json")
    res.status_code = status_code
    json.dump(val, res, cls=Serializer, indent=1)
    return res


def person_to_json(p: bmodels.Person, **kw):
    res = model_to_dict(p, **kw)
    res["fullname"] = p.fullname
    res["url"] = p.get_absolute_url()
    res["fpr"] = p.fpr
    res["uid"] = p.ldap_fields.uid
    res["cn"] = p.ldap_fields.cn
    res["mn"] = p.ldap_fields.mn
    res["sn"] = p.ldap_fields.sn
    return res


class People(APIVisitorMixin, APIView):
    def get(self, request, *args, **kw):
        # Pick what to include in the result based on auth status
        fields = ["fpr", "status", "status_changed", "created", "status_description"]
        if self.request.user.is_authenticated and self.request.user.is_dd:
            fields.append("email")
            if self.request.user.is_superuser:
                fields.append("fd_comment")

        try:
            res = []

            # Build query
            people = bmodels.Person.objects.all()

            val = request.GET.get("email", None)
            if val is not None:
                if val.startswith("/") and val.endswith("/"):
                    people = people.filter(email__iregex=val[1:-1])
                else:
                    people = people.filter(email__iexact=val)

            val = request.GET.get("uid", None)
            if val is not None:
                if val.startswith("/") and val.endswith("/"):
                    people = people.filter(ldap_fields__uid__iregex=val[1:-1])
                else:
                    people = people.filter(ldap_fields__uid__iexact=val)

            val = request.GET.get("name", None)
            if val is not None:
                if val.startswith("/") and val.endswith("/"):
                    val = val[1:-1]
                    people = people.filter(fullname__iregex=val)
                else:
                    people = people.filter(fullname__iexact=val)

            val = request.GET.get("fpr", None)
            if val is not None:
                people = people.filter(fprs__fpr__endswith=val)

            val = request.GET.get("status", None)
            if val is not None:
                people = people.filter(status=val)

            if self.request.user.is_superuser:
                val = request.GET.get("fd_comment", "")
                if val:
                    people = people.filter(fd_comment__icontains=val)

            for p in people.select_related("ldap_fields").order_by("fullname"):
                res.append(person_to_json(p, fields=fields))

            return json_response(dict(r=res))
        except Exception as e:
            # import traceback
            # traceback.print_exc()
            return json_response(dict(e=str(e)), status_code=500)


class Status(APIVisitorMixin, APIView):
    def _serialize_people(self, people):
        res = {}
        for p in people:
            debsso_identity = p.identities.filter(issuer="debsso").first()
            if debsso_identity is None:
                continue
            perms = p.perms
            rp = {
                "status": p.status,
            }
            if "am" in perms:
                rp["is_am"] = True
            res[debsso_identity.subject] = rp
        return json_response(dict(people=res))

    def get(self, request, *args, **kw):
        q_status = request.GET.get("status", None)
        q_person = request.GET.get("person", None)
        q_all = not any(bool(x) for x in (q_status, q_person))

        # Ensure that we got only one query
        if sum(bool(x) for x in (q_status, q_person)) > 1:
            return http.HttpResponseBadRequest("only one of status, person can be specified")

        # Enforce access restrictions
        if (q_status or q_all) and not self.request.user.is_authenticated:
            raise PermissionDenied

        # Get a QuerySet with the people to return
        persons = bmodels.Person.objects.all()
        if q_status:
            persons = persons.filter(status__in=q_status.split(","))
        elif q_person:
            persons = persons.filter(identities__issuer="debsso", identities__subject__in=q_person.split(","))
        elif q_all:
            pass
        else:
            return http.HttpResponseServerError("request cannot be understood")

        return self._serialize_people(persons)

    def post(self, request, *args, **kw):
        names = [str(x) for x in json.loads(request.body.decode("utf8"))]
        persons = bmodels.Person.objects.filter(identities__issuer="debsso", identities__subject__in=names)
        return self._serialize_people(persons)

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(Status, self).dispatch(*args, **kwargs)


class Whoami(APIVisitorMixin, APIView):
    """
    Return a JSON with information on the currently logged in user
    """
    def get(self, request, *args, **kw):
        if request.user.is_authenticated:
            data = model_to_dict(
                    self.request.user, fields=["cn", "mn", "sn", "email", "uid", "status", "status_changed"])
            data["fpr"] = self.request.user.fpr
            data["identities"] = [
                model_to_dict(i, fields=[
                    "issuer", "subject", "last_used", "profile", "picture", "fullname", "username"])
                for i in self.request.user.identities.all()
            ]
        else:
            data = {}
        res = http.HttpResponse(content_type="application/json")
        json.dump(data, res, indent=1, cls=Serializer)
        return res


class ExportIdentities(APIVisitorMixin, APIView):
    """
    Return a JSON with identity and status information for all users
    """
    def get(self, request, *args, **kw):
        from signon.models import Identity
        from backend import const

        if not self.request.user.is_authenticated or not self.request.user.is_staff:
            for addr in settings.IDENTITIES_EXPORT_ALLOW_IPS:
                log.debug("Trying to match %s against %s", addr, request.META["REMOTE_ADDR"])
                if request.META["REMOTE_ADDR"] == addr:
                    break
            else:
                log.warning("Remote address %s does not match %r",
                            request.META["REMOTE_ADDR"], settings.IDENTITIES_EXPORT_ALLOW_IPS)
                raise PermissionDenied

        by_person = {}
        for identity in Identity.objects.select_related("person", "person__ldap_fields").all():
            person = identity.person
            if person is None:
                continue

            person_data = by_person.get(person.pk)
            if person_data is None:
                if person.is_dd:
                    status = "debian_developer"
                elif person.status in (const.STATUS_DM, const.STATUS_DM_GA):
                    status = "debian_maintainer"
                elif person.status in (const.STATUS_EMERITUS_DD,):
                    status = "debian_emeritus"
                elif person.status in (const.STATUS_REMOVED_DD,):
                    status = "debian_removed_dd"
                else:
                    continue

                person_data = {
                    "full_name": person.fullname,
                    "email": person.email,
                    "status": status,
                    "ldap_uid": person.get_ldap_uid(),
                    "identities": [],
                }
                by_person[person.pk] = person_data

            person_data["identities"].append({
                "issuer": identity.issuer,
                "subject": identity.subject,
                "username": identity.username,
            })

        res = http.HttpResponse(content_type="application/json")
        json.dump(list(by_person.values()), res, indent=1, cls=Serializer)
        return res


class SalsaStatus(APIVisitorMixin, APIView):
    def get(self, request, *args, **kw):
        from signon.models import Identity
        identity = get_object_or_404(Identity, issuer="salsa", subject=self.kwargs["subject"])
        if identity.person is None:
            data = {
                "profile": None,
                "status": None,
                "uid": None,
            }
        else:
            data = {
                "profile": identity.person.get_absolute_url(),
                "status": identity.person.status,
                "uid": identity.person.get_ldap_uid(),
            }
        res = http.HttpResponse(content_type="application/json")
        json.dump(data, res, indent=1, cls=Serializer)
        return res

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

api/templates/api/doc.html
{% extends "nm2-base.html" %}
{% load i18n %}

{% block content %}

<h1>Debian New Member - API documentation</h2>

<h2>Authentication</h2>

<p>If you are using a browser Debian SSO authentication works as usual. If
you are using a script and public access is not enough for you, you can use
<a href="{% url 'apikeys:list' %}">API keys</a>. For example:
<pre>
curl -H "Api-Key: YourAPIKeyValue" {% url 'api:status' %}
</pre>
</p>

<h2>{% url 'api:people' %}</h2>

<p>Lists people known to the system.</p>

<p>GET parameters can be used to filter results:</p>

<table class="table table-sm">
    <thead>
        <tr><th>key</th><th>value</th></tr>
    </thead>
    <tbody>
        <tr><td>cn</td><td>First name</td></tr>
        <tr><td>mn</td><td>Middle name</td></tr>
        <tr><td>sn</td><td>Last name</td></tr>
        <tr><td>email</td><td>E-Mail</td></tr>
        <tr><td>uid</td><td>Debian account name</td></tr>
        <tr><td>fpr</td><td>OpenPGP key fingerprint</td></tr>
        <tr><td>status</td><td>Status in the project (as a tag like 'dd_u' or 'dm')</td></tr>
        <tr><td>fd_comment</td><td>FD comments (ignored unless authenticated as
                FD member or DAM)</td></tr>
    </tbody>
</table>

<p>All matches are case insensitive full string matches, except for 'status'
which matches exactly, and 'fpr' which matches case insensitively at the end of
the fingerprint.</p>

<p>For cn, mn, sn, email and uid, you can use <code>/value/</code> to match with a
case insensitive regular expression.</p>

<p>Results will only contain an 'email' field if the request is made by
authenticated people.</p>

<p>Example:</p>
<pre>
$ curl https://nm.debian.org/api/people?cn=/nric/
{
 "r": [
  {
   "status": "dd_u", 
   "uid": "gareuselesinge", 
   "created": "1136678400", 
   "url": "/public/person/gareuselesinge", 
   "mn": null, 
   "sn": "Tassi", 
   "fpr": "60D04388E3853643807B9507EE491C3E0123F2F2", 
   "status_changed": "1136678400", 
   "fullname": "Enrico Tassi", 
   "cn": "Enrico"
  }, 
  {
   "status": "dd_u", 
   "uid": "enrico", 
   "created": "1003968000", 
   "url": "/public/person/enrico", 
   "mn": null, 
   "sn": "Zini", 
   "fpr": "66B4DFB68CB24EBBD8650BC4F4B4B0CC797EBFAB", 
   "status_changed": "1003968000", 
   "fullname": "Enrico Zini", 
   "cn": "Enrico"
  }
 ]
}
</pre>

<h2>{% url 'api:status' %}</h2>

<p>Query the status of one, many or all people in the database</p>

<p>GET parameters can be used to control the results:</p>

<table class="table table-sm">
    <thead>
      <tr><th>Auth required</th><th>key</th><th>value</th></tr>
    </thead>
    <tbody>
    <tr><td>yes</td><td>status</td>
      <td>Get a list of all the people with the given status. You can use a
        comma-separated list of statuses, like <code>dd_nu,dd_u</code>.</td></tr>
    <tr><td>no</td><td>person</td>
      <td>Get the status of the person with the given SSO username. You can use
        a comma-separated list of SSO usernames.</td></tr>
    </tbody>
</table>

<p>If no parameter is specified, it returns a list of all known people. This
requires authentication.</p>

<p>Alternatively, you can POST a JSON list of SSO usernames, and get a reply
with the status of those people. This does not require authentication.</p>

<p>Example:</p>

<pre>
$ curl https://nm.debian.org/api/status --data '["enrico@debian.org","example-guest@users.alioth.debian.org"]'
{
 "people": {
  "enrico@debian.org": {
   "status": "dd_u", 
   "is_am": true
  },
  "example-guest@users.alioth.debian.org": {
   "status": "dm", 
  }
 }
}
</pre>


{% endblock %}