dm/urls.py
# coding: utf-8

from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="dm_index"),
    path('claim', views.Claim.as_view(), name="dm_claim"),
    path('claim/confirm/<token>', views.ClaimConfirm.as_view(), name="dm_claim_confirm"),
]

fprs/urls.py
from __future__ import annotations
from django.urls import path, re_path
from . import views

app_name = "fprs"

urlpatterns = [
    # Manage fingerprints
    path('person/<key>/', views.PersonFingerprints.as_view(), name="person_list"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/view/$', views.ViewKeyEndorsements.as_view(), name="view_endorsements"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/add/$', views.EndorseKey.as_view(), name="endorse"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/(?P<endorsement>[0-9]+)/raw/$', views.ViewRawKeyEndorsement.as_view(), name="view_raw_endorsement"),
    re_path('^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/endorsements/(?P<endorsement>[0-9]+)/delete/$', views.DeleteKeyEndorsement.as_view(), name="delete_endorsement"),
    # Activate fingerprints
    re_path(r'^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/activate/$', views.SetActiveFingerprint.as_view(),
            name="person_activate"),
]

nm2/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView, RedirectView
from backend.mixins import VisitorTemplateView
from django.conf import settings
from rest_framework import routers
from django.contrib import admin
import django.conf.urls
import backend.views as bviews
import process.views as pviews
import public.views as public_views
import nmlayout.views as nmviews

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'persons', bviews.PersonViewSet, "persons")
router.register(r'processes', pviews.ProcessViewSet, "processes")

django.conf.urls.handler403 = nmviews.Error403.as_view()
django.conf.urls.handler404 = nmviews.Error404.as_view()
django.conf.urls.handler500 = nmviews.Error500.as_view()


urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    path('i18n/', include('django.conf.urls.i18n')),
    path(r'', VisitorTemplateView.as_view(template_name='index.html'), name="home"),
    path('license/', VisitorTemplateView.as_view(template_name='license.html'), name="root_license"),
    path('faq/', VisitorTemplateView.as_view(template_name='faq.html'), name="root_faq"),
    path('login/', RedirectView.as_view(url="/signon/login"), name='legacy_login'),
    path('members/', public_views.Members.as_view(), name="members"),
    path('legacy/', include("legacy.urls")),
    path('person/', include("person.urls")),
    path('public/', include("public.urls")),
    path('am/', include("restricted.urls")),
    path('fprs/', include("fprs.urls")),
    path('process/', include("process.urls")),
    path('dm/', include("dm.urls")),
    path('api/', include("api.urls")),
    path('apikeys/', include("apikeys.urls")),
    path('keyring/', include("keyring.urls")),
    path('wizard/', include("wizard.urls")),
    path('mia/', include("mia.urls")),
    path('minechangelogs/', include("minechangelogs.urls")),
    path('sitechecks/', include("sitechecks.urls")),
    path('deploy/', include("deploy.urls")),
    path('rest/api/', include(router.urls)),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

person/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = "person"

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="index"),
    path('<key>/', views.Person.as_view(), name="show"),
    path('<key>/edit_ldap/', views.EditLDAP.as_view(), name="edit_ldap"),
    path('<key>/edit_bio/', views.EditBio.as_view(), name="edit_bio"),
    path('<key>/edit_email/', views.EditEmail.as_view(), name="edit_email"),
    # AM preferences editor
    path('<key>/amprofile/', views.AMProfile.as_view(), name="amprofile"),
    path('<key>/certificate/', views.Certificate.as_view(), name="certificate"),
    path('identities/', views.Identities.as_view(), name='identities_self'),
    path('identities/<key>/', views.Identities.as_view(), name='identities'),
]

process/urls.py
from __future__ import annotations
from django.urls import path
from . import views

urlpatterns = [
    path('', views.List.as_view(), name="process_list"),
    # AM Personal page
    path('am-dashboard/', views.AMDashboard.as_view(), name="process_am_dashboard"),
    path('create/<key>/', views.Create.as_view(), name="process_create"),
    path('<int:pk>/', views.Show.as_view(), name="process_show"),
    path('<int:pk>/intent/', views.ReqIntent.as_view(), name="process_req_intent"),
    path('<int:pk>/sc_dmup/', views.ReqAgreements.as_view(), name="process_req_sc_dmup"),
    path('<int:pk>/advocate/', views.ReqAdvocate.as_view(), name="process_req_advocate"),
    path('<int:pk>/am_ok/', views.ReqAM.as_view(), name="process_req_am_ok"),
    path('<int:pk>/keycheck/', views.ReqKeycheck.as_view(), name="process_req_keycheck"), # TODO: test
    path('<int:pk>/approval/', views.ReqApproval.as_view(), name="process_req_approval"), # TODO: test
    path('<int:pk>/add_log/', views.AddProcessLog.as_view(), name="process_add_log"),
    path('<int:pk>/<type>/statement/create/', views.StatementCreate.as_view(), name="process_statement_create"),
    path('<int:pk>/<type>/statement/<int:st>/delete/', views.StatementDelete.as_view(), name="process_statement_delete"),
    path('<int:pk>/<type>/statement/<int:st>/raw/', views.StatementRaw.as_view(), name="process_statement_raw"),
    path('<int:pk>/assign_am/', views.AssignAM.as_view(), name="process_assign_am"),
    path('<int:pk>/unassign_am/', views.UnassignAM.as_view(), name="process_unassign_am"),
    path('<int:pk>/mailbox/download/', views.MailArchive.as_view(), name="process_mailbox_download"), # TODO: test
    path('<int:pk>/mailbox/', views.DisplayMailArchive.as_view(), name="process_mailbox_show"), # TODO: test
    path('<int:pk>/update_keycheck/', views.UpdateKeycheck.as_view(), name="process_update_keycheck"), # TODO: test
    path('<int:pk>/download_statements/', views.DownloadStatements.as_view(), name="process_download_statements"), # TODO: test
    path('emeritus/', views.Emeritus.as_view(), name="process_emeritus_self"),
    path('emeritus/<key>/', views.Emeritus.as_view(), name="process_emeritus"),
    path('<int:pk>/cancel/', views.Cancel.as_view(), name="process_cancel"),
]

process/views.py
from __future__ import annotations
from django.utils.translation import gettext as _
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView
from django.utils.timezone import now
import django.utils.translation as translation
from django.db import transaction
from django import forms, http
from django.core.exceptions import PermissionDenied
from django.contrib import messages as django_messages
from django.urls import reverse
from rest_framework import viewsets
from backend.shortcuts import build_absolute_uri
from backend.mixins import VisitorMixin, VisitPersonMixin, TokenAuthMixin
from backend import const
import backend.models as bmodels
from nm2.lib import assets
import nm2.lib.forms
from .mixins import VisitProcessMixin, RequirementMixin, StatementMixin
import datetime
import requests
import shlex
from . import models as pmodels
from .forms import StatementForm
from .serializers import ProcessSerializer
from . import ops as pops


# Catcher for HTTPError
def _catch_http_error(request, e, ret_dest):
    django_messages.add_message(
        request,
        django_messages.ERROR,
        _("The server encountered an error: {}").format(e),
    )
    return redirect(ret_dest)


class ProcessViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Export process information
    """
    queryset = pmodels.Process.objects.filter(
        closed_time__isnull=True).order_by("started")
    serializer_class = ProcessSerializer


class List(VisitorMixin, TemplateView):
    """
    List active and recently closed processes
    """
    assets = [assets.DataTablesBootstrap4]
    template_name = "process/list.html"

    def get_context_data(self, **kw):
        ctx = super(List, self).get_context_data(**kw)
        ctx["current"] = pmodels.Process.objects.filter(
            closed_time__isnull=True).order_by("applying_for").select_related("person")
        cutoff = now() - datetime.timedelta(days=30)
        ctx["last"] = pmodels.Process.objects.filter(
            closed_time__gte=cutoff).order_by("-closed_time").select_related("person")
        return ctx


class AMDashboard(VisitorMixin, TemplateView):
    require_visitor = "am"
    template_name = "process/amdashboard.html"

    def _show_process(self, process):
        """
        Return True if the process should be shown in the dashboard, False if
        it should not.
        """

        if process.frozen_by_id is not None or process.approved_by_id is not None:
            return True

        if process.hide_until and process.hide_until > now():
            return False

        if process.applying_for in (const.STATUS_EMERITUS_DD, const.STATUS_REMOVED_DD):
            return True

        for_ga = False
        if process.applying_for == const.STATUS_DC_GA:
            for_ga == (process.person.status == const.STATUS_DC)
        elif process.applying_for == const.STATUS_DM_GA:
            for_ga == (process.person.status == const.STATUS_DM)

        for req in process.requirements.all():
            if req.type == "intent":
                if not req.approved_by_id:
                    return False
                # Hide all processes with a statement of intent approved less
                # than 4 days ago
                if not for_ga and req.approved_time + datetime.timedelta(days=4) > now():
                    return False
            if req.type in ("sc_dmup", "advocate", "keycheck") and not req.approved_by_id:
                return True
            if req.type == "am_ok":
                if req.approved_by_id is None and process.current_am_assignment:
                    return False

        return True

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        import process.models as pmodels
        from sitechecks.models import Inconsistency
        processes = []
        approved_processes = []
        fd_approved_processes = []
        for p in pmodels.Process.objects.filter(closed_time__isnull=True).order_by("applying_for"):
            # Shows in fd_approved_processes even hidden processes, so DAM can't miss these
            if p.applying_for in ['dd_nu', 'dd_u']:
                if p.approved and p.approved_by.am_or_none and not p.approved_by.am.is_dam and not p.rt_ticket:
                    fd_approved_processes.append(p)
                    continue
            if not self._show_process(p):
                continue
            if p.approved:
                approved_processes.append(p)
            else:
                processes.append(p)
        ctx["current_processes"] = processes
        ctx["approved_processes"] = approved_processes
        ctx["fd_approved_processes"] = fd_approved_processes

        ctx["am_available"] = bmodels.AM.list_available(free_only=True)

        today = now().date()
        ctx["inconsistencies"] = [
            i for i in Inconsistency.objects.filter(last_seen__gte=today)
                                            .order_by("-last_seen", "person", "process", "tag", "text")
            if (i.ignore_until is None or i.ignore_until < today)
        ]

        for a in pmodels.AMAssignment.objects.filter(
                            am=self.request.user.am, process__closed_time__isnull=True, unassigned_by__isnull=True) \
                        .select_related("process") \
                        .order_by("process__started"):
            if a.paused:
                ctx.setdefault("am_prog_hold", []).append(a.process)
            else:
                ctx.setdefault("am_prog_am", []).append(a.process)

        return ctx


class Create(VisitPersonMixin, FormView):
    """
    Create a new process
    """
    require_visit_perms = "request_new_status"
    template_name = "process/create.html"

    def get_context_data(self, **kw):
        ctx = super(Create, self).get_context_data(**kw)
        current = []
        current.extend(pmodels.Process.objects.filter(
            person=self.person, closed_time__isnull=True))
        ctx["current"] = current
        ctx["wikihelp"] = "https://wiki.debian.org/DebianDeveloper/JoinTheProject/NewMember/StatusChangeStep"
        return ctx

    def get_form_class(self):
        whitelist = self.person.possible_new_statuses
        choices = [(x.tag, x.ldesc)
                   for x in const.ALL_STATUS if x.tag in whitelist]
        if not choices:
            raise PermissionDenied

        class Form(nm2.lib.forms.BootstrapAttrsMixin, forms.Form):
            applying_for = forms.ChoiceField(
                label=_("Apply for status"), choices=choices, required=True)
        return Form

    def form_valid(self, form):
        applying_for = form.cleaned_data["applying_for"]
        if applying_for == const.STATUS_EMERITUS_DD:
            return redirect(reverse("process_emeritus", args=[self.person.lookup_key]))

        op = pops.ProcessCreate(
            person=self.person, applying_for=applying_for, audit_author=self.request.user)
        op.execute(self.request)

        return redirect(op.new_process.get_absolute_url())


class Show(VisitProcessMixin, TemplateView):
    """
    Show a process
    """
    template_name = "process/show.html"

    def get_context_data(self, **kw):
        ctx = super(Show, self).get_context_data(**kw)
        ctx["status"] = self.compute_process_status()
        ctx["picture"] = self.person.get_picture_url()
        return ctx


class AddProcessLog(VisitProcessMixin, View):
    """
    Add an entry to the process or requirement log
    """
    @transaction.atomic
    def post(self, request, *args, **kw):
        logtext = request.POST.get("logtext", "").strip()
        action = request.POST.get("add_action", "undefined")
        req_type = request.POST.get("req_type", None)

        if req_type:
            requirement = get_object_or_404(
                pmodels.Requirement, process=self.process, type=req_type)
            target = requirement
        else:
            requirement = None
            target = self.process

        visit_perms = target.permissions_of(self.request.user)

        op = None
        if action in ("log_private", "log_public"):
            if "add_log" not in visit_perms:
                raise PermissionDenied
            if logtext:
                op_args = {}
                if req_type:
                    op_args["requirement"] = requirement
                else:
                    op_args["process"] = self.process
                op = pops.ProcessAddLogEntry(
                    audit_author=self.request.user,
                    audit_notes=logtext,
                    is_public=action == "log_public",
                    **op_args)
        elif action == "req_unapprove":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.RequirementUnapprove(
                audit_author=self.request.user, audit_notes=logtext or "Requirement unapproved",
                requirement=requirement)
        elif action == "req_approve":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.RequirementApprove(
                audit_author=self.request.user, audit_notes=logtext or "Requirement approved", requirement=requirement)
        elif action == "proc_pause":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.ProcessPause(
                audit_author=self.request.user, audit_notes=logtext or "Process paused", process=self.process)
        elif action == "proc_unpause":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.ProcessUnpause(
                audit_author=self.request.user, audit_notes=logtext or "Process resumed", process=self.process)
        elif action == "proc_freeze":
            if action not in visit_perms:
                raise PermissionDenied

process/templates/process/amdashboard.html
{% extends "process/nm2-base.html" %}
{% load i18n %}
{% load nm %}

{% block head %}
{{block.super}}
<style type="text/css">
ul.horizontal {
    list-style-type: none;
}
ul.horizontal li {
    display: inline;
}
{% comment %}
table.inconsistency_table tbody {
  white-space: nowrap;
}
{% endcomment %}
</style>
{% endblock %}

{% block content %}

<h1>{% trans "Debian New Member" %}</h1>

<p>{% trans "Currently the database thinks you have the following functions:" %}</p>
<ul>
    {% if user.am.is_am_ctte %}<li>{% trans "New Member Committee" %}</li>{% endif %}
    {% if user.am.is_am %}<li>{% blocktrans with visitor_am_slots=user.am.slots %}Application Manager with {{ visitor_am_slots }} slots{% endblocktrans %}</li>{% endif %}
    {% if user.am.is_fd %}<li>{% trans "Front Desk" %}</li>{% endif %}
    {% if user.am.is_dam %}<li>{% trans "Debian Account Manager" %}</li>{% endif %}
</ul>

{% if user.is_superuser %}

<h2 class="mt-3">{% trans "Front desk" %}</h2>

<h3 class="mt-3">{% trans "Processes needing attention" %}</h3>

{% include "process/process_list.html" with procs=current_processes skip_caption=True %}

{% if fd_approved_processes %}
<h3 class="mt-3">{% trans "Debian Developer processes approved by FD" %}</h3>

{% include "process/process_list.html" with procs=fd_approved_processes skip_caption=True %}
{% endif %}

{% if approved_processes %}
<h3 class="mt-3">{% trans "Processes approved but not yet closed" %}</h3>

{% include "process/process_list.html" with procs=approved_processes skip_caption=True %}
{% endif %}

{% if inconsistencies %}
<h3 class="mt-3">Current inconsistencies</h3>

{% include "sitechecks/inconsistency_table.html" with inconsistencies=inconsistencies %}

<a href="{% url 'sitechecks_list' %}">Full list</a>

{% endif %}

<h3 class="mt-3">{% trans "Application manager availability" %}</h3>

{% if am_available %}

<p>{% trans "The following managers have free slots (#free/#slots):" %}</p>
<ul class="horizontal">
    {% for a in am_available %}
    <li><a href="{% url 'person:amprofile' key=a.person.lookup_key %}">{{a.person.ldap_fields.uid}}</a>
        ({{a.stats_free}}/{{a.slots}})</li>
    {% endfor %}
</ul>
{% else %}
<p>{% trans "Currently there are no free application managers" %}.</p>
{% endif %}

{% endif %}

{# only show application manager section if the current user either has AM slots or any existing process assigned #}
{% if user.am.slots or am_prog_am or am_prog_hold %}
<h2 class="mt-3">{% trans "Application Manager" %}</h2>

<p>{% blocktrans with visitor_uid=user.ldap_fields.uid %}Hello <b>{{visitor_uid}}</b>,
here is a list of New Member applicants who are assigned to you:{% endblocktrans %}</p>

<h3 class="mt-3">{% trans "Applicants to process" %}</h3>

<p>{% blocktrans %}The following applicants are assigned to you (ordered by the
date you accepted them as NMs):{% endblocktrans %}</p>
{% include "process/process_list.html" with procs=am_prog_am skip_caption=True %}

<h3 class="mt-3">{% trans "Applicants on Hold" %}</h3>

<p>{% blocktrans %}Applicants who appear here have some issue with completing
the process but are expected to be able to work around that soon (ordered by
hold date).{% endblocktrans %}</p>
{% include "process/process_list.html" with procs=am_prog_hold skip_caption=True %}

{% endif %}

{% endblock %}

process/templates/process/explain_statement_intent.html
{% load nm %}
{% load i18n %}

<p>{% trans "The most important requirement for changing status in Debian is to make sure that a person actually intends to do so." %}</p>

{% if edit %}

<p>{% blocktrans context "to a particular mailing list" %}Paste a signed Statement of Intent in the form below, and
    it will automatically be posted to {% endblocktrans %}
    {% if process.applying_for == "dd_e" %}<a href="https://lists.debian.org/debian-private/">debian-private</a>
    {% else %}<a href="https://lists.debian.org/debian-newmaint/">debian-newmaint</a>
    {% endif %}.
</p>

<p>{% trans "An example Statement of Intent can be something like this:" %}

<pre>
{% language 'en' %}
{% if process.applying_for == "dd_e" %}
Dear fellow developers,

As I am not currently active in Debian, I request to move to the Emeritus
status.

So long, and thanks for all the fish.
{% else %}
For nm.debian.org, at {{now|date:"Y-m-d"}}:
I would like to apply to change my status in Debian to {{process.applying_for|desc_status}}.
I have worked on X and Y for a while and I would like to be able to Z.
</pre>
</p>
{% endif %}
{% endlanguage %}


{% endif %}

process/templates/process/req_approval.html
{% extends "process/nm2-base.html" %}
{% load i18n %}

{% block content %}

<h1>{{type_desc}}</h1>

{% include explain_template with edit=False %}

{% include "process/requirement_status_widget.html" %}

<h2>{% trans "Signed statements" %}</h2>

{% include "process/statement_table_widget.html" %}

<h2>{% trans "Log" %}</h2>

{% include "process/log_widget.html" with entries=requirement.log.all %}

{% endblock %}

process/templates/process/req_keycheck.html
{% extends "process/nm2-base.html" %}
{% load i18n %}
{% load nm %}

{% block content %}

<h1>{{type_desc}}</h1>

{% include "process/requirement_status_widget.html" %}

<!-- explanation of requirement: -->
<p>{% blocktrans %}Every Debian member needs a GPG key of sufficient strength. In addition, all keys should be certified
   so we can link them to a real-world identity.{% endblocktrans %}</p>
<p>{% trans "The normal requirements are:" %}</p>
<ul>
  <li>{% trans "the key should be type RSA and version 4 or greater" %}</li>
  <li>{% trans "the key should have the sign, certify and encrypt capabilities (subkeys are encouraged)" %}</li>
  <li>{% trans "the primary cryptographic material should be at least 4096 bits" %}</li>
  <li>{% trans "the UIDs used by an applicant to work in the project should be signed by at least two existing Debian members (1 for DM applications)" %}</li>
  <li>{% trans "as an alternative to the previous requirement, the key can be endorsed (see link at the bottom of the page) by multiple Debian Members (the number of required endorsements depends on the endorsement's age and nature)" %}</li>
  <li>{% trans "pseudonyms or anonymity are acceptable in certain circumstances" %}</li>
</ul>
<p>{% trans "If the key does not meet these requirements, and you would struggle to create one which does, contact Front Desk." %}</p>
<p>{% blocktrans %}Keys are first searched in <code>hkps://keyring.debian.org</code>. If no key is found,
   then the key will be imported from <code>hkps://keyserver.ubuntu.com/</code>. Please ensure that you
   have sent your key to Ubuntu's key server. Sending public keys to keyring.debian.org will only work if your
   key is already in Debian's keyring and will only be taken into account after the Keyring Maintainers
   updated it. For Debian Maintainers and Developers, please remember to send your key to both servers.
   {% endblocktrans %}</p>
<p><b>{% trans "This check will be approved manually by Front Desk as the application progresses." %}</b></p>

<h2>{% trans "Key check results" %}</h2>

{% if status.keycheck %}
<table class="table table-sm">
  <tbody>
    <tr>
      <th>{% trans "OpenPGP fingerprint" %}</th>
      <td>{{person.fpr|fingerprint}}{% if "edit_fpr" in visit_perms %} (<a href="{% url 'fprs:person_list' key=person.lookup_key %}">{% trans "manage" context "verb; link to manage this person" %}</a>){% endif %}</td>
    </tr>
    {% with status.keycheck as keycheck %}
    <tr>
      <th>{% trans "Main key" %}</th>
      <td class="keycheck_key">
          <b>{{keycheck.main.remarks}}</b> (last updated: {{keycheck.updated|date:"Y-m-d H:i T"}})
          {% if "update_keycheck" in visit_perms %}
          <form class="inline" action="{% url 'process_update_keycheck' pk=process.pk %}" method="POST">{% csrf_token %}
            <button class="btn btn-outline-primary btn-sm" type="submit">{% trans "Update" %}</button>
          </form>
          {% endif %}
      </td>
    </tr>
    {% for uid in keycheck.uids %}
    <tr>
      <th>{% trans "UID" %} {{uid.name}}</th>
      <td class="keycheck_uid">
        <b>{{uid.remarks}}</b>, <i>{{uid.sigs_no_key}}</i> {% trans "non-DD sigs," %}
        {% if uid.sigs_ok|length > 10 %}
        {% trans "first 10 of" %} <b>{{uid.sigs_ok|length}}</b> {% trans "DD sigs:" %}
        {% else %}
        <b>{{uid.sigs_ok|length}}</b> {% trans "DD sigs:" %}
        {% endif %}
        <ul class="packed">
          {% for s in uid.sigs_ok|slice:":10" %}
          <li>{{s.4}}: {{s.9}}</li>
          {% empty %}
          <li>{% trans "none" %}</li>
          {% endfor %}
        </ul>
      </td>
    </tr>
    {% endfor %}
    {% endwith %}
  </tbody>
</table>
{% else %}
<p>{% trans "No key check results available." %}</p>
{% endif %}

<h2>{% trans "Active key endorsements" %}</h2>

<table class="table table-sm">
  <thead>
    <tr>
      <th>{% trans "Endorsed by" %}</th>
      <th>{% trans "Date" %}</th>
      <th>{% trans "Statement" %}</th>
      <th>{% trans "Actions" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for e in endorsements %}
    <tr>
      <td>{{e.author.a_link}}</td>
      <td>{{e.date|date:"Y-m-d"}}<br><small>({{e.date|timesince}} ago)</small></td>
      <td>
        <pre class="inline-statement mb-0">{{e.text_clean}}</pre>
        <small><i>{% if e.endorsing_fpr.fpr %}{% trans "Signed with key" %} {{e.endorsing_fpr.fpr|fingerprint}}{% else %}{% trans "Unsigned" %}{% endif %}</i></small>
      </td>
      <td>
        <a class="btn btn-sm btn-primary" href="{% url 'fprs:view_raw_endorsement' key=person.lookup_key fpr=person.fpr endorsement=e.pk %}">{% trans "View raw" %}</a>
        {% if e.author == user or user.is_superuser %}
        <a class="btn btn-sm btn-warning fprs:endorsement_delete" href="{% url 'fprs:delete_endorsement' key=person.lookup_key fpr=person.fpr endorsement=e.pk %}">{% trans "Delete" %}</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
  {% if "endorse_key" in visit_perms and person.fpr is not None %}
  <tfoot>
    <tr>
      <td colspan="3">
        <a class="btn btn-primary" href="{% url 'fprs:endorse' key=person.lookup_key fpr=person.fpr %}">Add your endorsement</a>
      </td>
    </tr>
  </tfoot>
  {% endif %}
</table>

<h2>{% trans "Log" %}</h2>

{% include "process/log_widget.html" with entries=requirement.log.all %}

{% endblock %}